import "./global.css";
import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        {children}
        <Script type="text/javascript" src="/webOSTV-dev.js" />
        <Script type="text/javascript" src="/webOSTV.js" />
      </body>
    </html>
  );
}
